### ISSUE TITLE
 emm你这个意思就是，反正也听不懂，全都一股脑放进去吧？[笑哭]

### ISSUE THREAD

**Issue by AmberBufei** [heixiaobai/rainbow-fart-voice-pack#2]
emm你这个意思就是，反正也听不懂，全都一股脑放进去吧？[笑哭]
![image](https://user-images.githubusercontent.com/26531400/87503027-c1ad2c80-c695-11ea-9388-441a053df88d.png)

![image](https://user-images.githubusercontent.com/26531400/87503076-d8538380-c695-11ea-9a3b-5a2cf70d844b.png)
![image](https://user-images.githubusercontent.com/26531400/87503088-de496480-c695-11ea-9f8d-2b82e3e7a2de.png)

**Comment by heixiaobai** [comment]
嘿兄弟，你找错项目了，我制作的这个是区分语言的

**Comment by heixiaobai** [comment]
嘿兄弟，你找错项目了，我制作的这个是区分语言的
